#!/bin/bash

sudo add-apt-repository ppa:fcitx-team/nightly
sudo apt-get update #更新一下源
sudo apt-get install fcitx fcitx-bin fcitx-config-common fcitx-config-gtk2 fcitx-data fcitx-frontend-gtk2 fcitx-frontend-gtk3 fcitx-frontend-qt4 fcitx-frontend-qt5 fcitx-libs fcitx-libs-gclient fcitx-libs-qt fcitx-libs-qt5 fcitx-module-dbus fcitx-module-kimpanel fcitx-module-x11 fcitx-modules fcitx-table fcitx-ui-classic libopencc1  #安装fcitx
wget 'http://download.ime.sogou.com/1432523940/sogoupinyin_1.2.0.0056_amd64.deb?st=eBzbU41kwt18FmRq3q5sqA&e=1436431615&fn=sogoupinyin_1.2.0.0056_amd64.deb' -O $toolsDir/sogoupinyin_1.2.0.0056_amd64.deb
if [ "$?" == "0" ]; then
	echo -e "下载完成"
else
	echo -e "下载失败，正在重新尝试"
	wget 'http://download.ime.sogou.com/1432523940/sogoupinyin_1.2.0.0056_amd64.deb?st=eBzbU41kwt18FmRq3q5sqA&e=1436431615&fn=sogoupinyin_1.2.0.0056_amd64.deb' -O $toolsDir/sogoupinyin_1.2.0.0056_amd64.deb
fi
sudo dpkg -i $toolsDir/sogoupinyin_1.2.0.0056_amd64.deb #安装sogou_pinyin
echo "完成，按回车键继续"
read anykey
